# Site settings
title: Soundview Servicenter
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

hours: [ { day: Monday, start: "7:00AM", end: "8:00PM" },
      { day: Tuesday, start: "7:00AM", end: "8:00PM" },
      { day: Wednesday, start: "7:00AM", end: "8:00PM" },
      { day: Thursday, start: "7:00AM", end: "8:00PM" },
      { day: Friday, start: "7:00AM", end: "8:00PM" },
      { day: Saturday, start: "7:00AM", end: "6:00PM" },
      { day: Sunday, start: "7:00AM", end: "4:00PM"} ]
